# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensor_ipc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10tensor_ipc.proto\x12\x0bneuroweaver\x1a\x1cgoogle/protobuf/struct.proto\"@\n\x06Tensor\x12\x0c\n\x04name\x18\x01 \x02(\t\x12(\n\x04rows\x18\x02 \x03(\x0b\x32\x1a.google.protobuf.ListValue\"1\n\tTensorMap\x12$\n\x07tensors\x18\x01 \x03(\x0b\x32\x13.neuroweaver.Tensor')



_TENSOR = DESCRIPTOR.message_types_by_name['Tensor']
_TENSORMAP = DESCRIPTOR.message_types_by_name['TensorMap']
Tensor = _reflection.GeneratedProtocolMessageType('Tensor', (_message.Message,), {
  'DESCRIPTOR' : _TENSOR,
  '__module__' : 'tensor_ipc_pb2'
  # @@protoc_insertion_point(class_scope:neuroweaver.Tensor)
  })
_sym_db.RegisterMessage(Tensor)

TensorMap = _reflection.GeneratedProtocolMessageType('TensorMap', (_message.Message,), {
  'DESCRIPTOR' : _TENSORMAP,
  '__module__' : 'tensor_ipc_pb2'
  # @@protoc_insertion_point(class_scope:neuroweaver.TensorMap)
  })
_sym_db.RegisterMessage(TensorMap)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TENSOR._serialized_start=63
  _TENSOR._serialized_end=127
  _TENSORMAP._serialized_start=129
  _TENSORMAP._serialized_end=178
# @@protoc_insertion_point(module_scope)
