# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dataflow.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64\x61taflow.proto\x12\x08toroflow\x1a\x1cgoogle/protobuf/struct.proto\"\xa2\x02\n\tComponent\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\nlogical_id\x18\x02 \x01(\r\x12\x13\n\x0bparallelism\x18\x03 \x01(\r\x12\x10\n\x08\x62ranches\x18\x04 \x01(\r\x12\x35\n\x11\x63hild_logical_ids\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.ListValue\x12\x16\n\x0eis_accelerated\x18\x06 \x01(\x08\x12\x12\n\naccel_impl\x18\x07 \x01(\t\x12\x13\n\x0btarget_impl\x18\x08 \x01(\t\x12\x15\n\rcpp_impl_file\x18\t \x01(\t\x12\x13\n\x0b\x63pp_impl_fn\x18\n \x01(\t\x12\x14\n\x0cpy_impl_file\x18\x0b \x01(\t\x12\x12\n\npy_impl_fn\x18\x0c \x01(\t\"3\n\x08\x64\x61taflow\x12\'\n\ncomponents\x18\x01 \x03(\x0b\x32\x13.toroflow.Componentb\x06proto3')



_COMPONENT = DESCRIPTOR.message_types_by_name['Component']
_DATAFLOW = DESCRIPTOR.message_types_by_name['dataflow']
Component = _reflection.GeneratedProtocolMessageType('Component', (_message.Message,), {
  'DESCRIPTOR' : _COMPONENT,
  '__module__' : 'dataflow_pb2'
  # @@protoc_insertion_point(class_scope:toroflow.Component)
  })
_sym_db.RegisterMessage(Component)

dataflow = _reflection.GeneratedProtocolMessageType('dataflow', (_message.Message,), {
  'DESCRIPTOR' : _DATAFLOW,
  '__module__' : 'dataflow_pb2'
  # @@protoc_insertion_point(class_scope:toroflow.dataflow)
  })
_sym_db.RegisterMessage(dataflow)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COMPONENT._serialized_start=59
  _COMPONENT._serialized_end=349
  _DATAFLOW._serialized_start=351
  _DATAFLOW._serialized_end=402
# @@protoc_insertion_point(module_scope)
